### ISSUE TITLE
[marketing] launch

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#126]
- [x] create blog post
- [x] formalize the way we spell dat-desktop
- [x] formalized one sentence description
- [x] update dat-desktop repo with new screenshot
- [ ] climate use case @maxogden 
- [x] update dat-desktop repo with links to download page (github releases)
- [x] deploy latest datproject.org
- [x] tweet about the thing
- [ ] ~~Newsletter (@karissa)~~

**Comment by Kriesse** [comment]
Correct Spelling: `Dat Desktop`

**Comment by Kriesse** [comment]
Preparing datproject.org for the launch with @karissa here https://github.com/datproject/website/tree/desktop-app-launch

**Comment by Kriesse** [comment]
@karissa Can you help with the 1-sentence description? Maybe also have a slightly longer, 3-5 sentence one? 

I think this is important to stick with the same, consistent wording, to establish a clear idea of what Desktop is, within the team and most importantly our audience. We should aim to use this on the blog, tweets, front page etc.

**Comment by Kriesse** [comment]
ping @maxogden – what was the last point in the checklist ("climate use case") about again? Is that done?

**Comment by Kriesse** [comment]
ping @karissa – thoughts about tweets/newsletters/blogpost? happy to help, let me know what is needed!

**Comment by karissa** [comment]
tweet:  'Today we released Dat Desktop for Mac OSX. Come give it a spin! <link>'
newsletter: blog post text

**Comment by karissa** [comment]
dat is 'Dat is the package manager for data. Easily share and version control data using our powerful command line tool and javascript library. '

so dat desktop could be 

'Dat Desktop is for easily downloading, sharing, and version controlling data without a central servers. Secure, distributed, fast.'

**Comment by Kriesse** [comment]
@karissa Love the description!
For the newsletter: I don't think the blogpost works well as a newsletter. Would like to design a simple template for this – do we have a Mailchimp (or similar) account I can use? 

@maxogden The climate dataset is the NASA one? It's still not working for me when I try to download it with Dat Desktop.

**Comment by karissa** [comment]
OK @Kriesse ,-- We have a tinyletter account, does that work? Or do you need something closer to mailchimp? I'll give you the creds.

**Comment by juliangruber** [comment]
created a new issue for the newsletter here: https://github.com/datproject/dat-desktop/issues/264

**Comment by juliangruber** [comment]
created a new issue for the climate use case here: https://github.com/datproject/dat-desktop/issues/265
